apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-okay-clusters
  namespace: gitops-apps
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels: {}
