apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: dev-clusters-httpass-auth
  namespace: day2ops-policies
  annotations:
    apps.open-cluster-management.io/git-path: authentication/
    apps.open-cluster-management.io/git-branch: infra
spec:
  channel: gitops-apps/acm-gitops-github
  placement:
    local: true
